# Generated by Django 2.2.2 on 2022-05-31 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '轮播图表'},
        ),
        migrations.AlterModelTable(
            name='banner',
            table='luffy_banner',
        ),
    ]
